[tool.poetry]
name = "fastapi-course"
version = "0.1.0"
description = ""
authors = ["James <jamesbrendamour7@yahoo.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
